// Generated by scripts/build-girth-model.mjs. Girths in cm from sex, height (cm), weight (kg), age and body fat.
// Sources: ANSUR II public data (US Army, 2012; 1,986 women, 4,082 men) and, for the effect of body fat in men,
// Kaggle fedesoriano/body-fat-prediction-dataset (252 men, underwater weighing). Coefficients: [1, height, weight, age, BMI].
export const GIRTH_MODEL = {"female":{"n":1986,"range":{"height":[146.3,179.3],"weight":[44.2,101.9],"age":[18,53]},"coef":{"chest":[8.66275,0.213875,0.0759965,0.123571,1.66568],"waist":[0.636977,0.135968,0.17915,0.112005,1.87993],"hip":[-7.89837,0.388036,0.00704087,0.00462436,1.8129],"thigh":[3.51458,0.143681,0.109127,-0.0228918,1.09706],"calf":[9.82448,0.0791098,0.0665458,-0.0414158,0.443528],"arm":[4.76625,0.038398,0.0695984,0.0187403,0.560101],"neck":[12.6986,0.0609964,0.0187134,0.0197403,0.333722]},"rmse":{"chest":4.11,"waist":4.73,"hip":2.9,"thigh":2.25,"calf":1.66,"arm":1.38,"neck":1.2}},"male":{"n":4082,"range":{"height":[158,194.6],"weight":[55.6,129.2],"age":[18,55]},"coef":{"chest":[23.7502,0.153339,0.166746,0.107301,1.36146],"waist":[20.9143,0.0112148,0.338185,0.194772,1.31389],"hip":[7.41564,0.27989,0.100231,-0.0512912,1.38539],"thigh":[17.9354,0.05881,0.160833,-0.0900919,0.838413],"calf":[11.9528,0.0649941,0.0506167,-0.0295887,0.44868],"arm":[13.9185,0.0148765,0.0835545,-0.00772496,0.446773],"neck":[19.2187,0.0348796,0.0395532,0.0278511,0.368337]},"rmse":{"chest":3.06,"waist":4.04,"hip":2.56,"thigh":2.11,"calf":1.58,"arm":1.87,"neck":1.46},"fat":{"n":249,"expected":[-220.384,1.08646,-1.20139,0.135847,5.39071],"rmse":5.33,"perPoint":{"chest":0.06,"waist":0.362,"hip":0.028,"thigh":0.05,"arm":-0.014}}}};
const clamp = (v, [a, b]) => Math.min(b, Math.max(a, v));

// Girths a typical person with these numbers has. arm: relaxed upper arm (ANSUR measures it flexed, ~1.5 cm more).
export function predictGirths({sex, height, weight, age, body_fat: fat}) {
  if (!height || !weight) return {};
  const m = GIRTH_MODEL[sex === 'female' ? 'female' : 'male'], h = clamp(height, m.range.height), w = clamp(weight, m.range.weight), a = clamp(age || 30, m.range.age);
  const x = [1, h, w, a, w / (h / 100) ** 2], dot = c => c.reduce((s, v, i) => s + v * x[i], 0);
  const g = Object.fromEntries(Object.entries(m.coef).map(([k, c]) => [k, dot(c)]));
  g.arm -= 1.5;
  if (fat != null && m.fat) {
    // Men: more (or less) fat than usual for this height and weight -> girths shift by the measured effect.
    const extra = Math.max(-12, Math.min(12, fat - dot(m.fat.expected)));
    for (const [k, per] of Object.entries(m.fat.perPoint)) g[k] += per * extra;
  } else if (fat != null) {
    // Women: the US Navy body-fat formula ties waist + hip - neck to body fat and height. Use only the difference between
    // this body fat and the usual one for this BMI and age (Deurenberg 1991), so the formula's own offset cancels out.
    const inch = 2.54, sum = f => 10 ** ((f + 78.387 + 97.684 * Math.log10(h / inch)) / 163.205) * inch;
    const usual = 1.2 * x[4] + 0.23 * a - 5.4, gap = Math.max(-15, Math.min(15, sum(fat) - sum(usual)));
    g.waist += gap * 0.6; g.hip += gap * 0.4;
  }
  delete g.neck;
  return Object.fromEntries(Object.entries(g).map(([k, v]) => [k, Math.round(v * 10) / 10]));
}
